### ISSUE TITLE
Cafeteria page disclaimer for academic breaks

### ISSUE THREAD

**Issue by balaktsis** [acmauth/StudentCompanion#201]
Όταν κλείνει η λέσχη -ιδίως για καλοκαιρινές διακοπές- να σταματήσει να εμφανίζει "ανοιχτή".

**Comment by balaktsis** [comment]
Μια λύση θα ήταν να κρατάμε στην cache στην ημερονηνία κάθε Δευτέρας (το γράφει το menu στο scraping) και αν παρατηρηθεί η ίδια ημερομηνία να ενεργοποιηθεί ένα flag που να κρατάει το label "Κλειστή" μέχρι να ξαναδεί νέα ημερομηνία στο scraping.

**Comment by balaktsis** [comment]
![image](https://github.com/acmauth/StudentCompanion/assets/74056421/ca57b708-d68b-41a4-8c18-3dbaf6d0f9ae)

**Comment by itsMyrto** [comment]
Έτρεξα και στο κινητό και στο web το branch και παίρνω: 
![Screenshot_Mozilla Firefox_1](https://github.com/user-attachments/assets/b5cdf290-3dca-473a-8b5d-6667b4b5518d)
