### ISSUE TITLE
Navbar exists on login page 

### ISSUE THREAD

**Issue by balaktsisc** [acmauth/StudentCompanion#57]
Vanish navbar. Also, what's up with the image alignment?
![image](https://github.com/acmauth/StudentCompanion/assets/74056421/73a81f33-4d2a-4512-8c45-66cdeb36ecb7)
![image](https://github.com/acmauth/StudentCompanion/assets/74056421/e6b83d40-e5cd-4908-ad42-d0a7ef38e5f0)

**Comment by neron-png** [comment]
Fixed w/ https://github.com/acmauth/StudentCompanion/commit/b742c89bcfca6bbf5f35aa4d54b78bd574c40ad4
